[tool.mypy]
ignore_missing_imports = true
strict_optional = true
warn_unused_ignores = true
warn_incomplete_stub = true
warn_redundant_casts = true

check_untyped_defs = true
disallow_subclassing_any = true
disallow_untyped_defs = true

[tool.isort]
line_length = 120
profile = 'black'
py_version=38
skip_glob = [
  "sources/**"
]

[tool.black]
preview = true
line-length = 120
target-version = ['py311']

# regex
exclude = '''
/(
  \.git |
  sources
)/
'''

[tool.ruff]
select = ["E", "F", "W"]
line-length = 120
target-version = 'py311'
