# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Main

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  job_lint:
    name: Linting (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Do linting
        run: |
          pushd typings/ || exit

          mypy \
            -m sublime \
            -m sublime_plugin \
            -m _sublime_types \
            --

          # rename *.pyi to *.py
          for f in *.pyi; do
              mv -- "$f" "${f%.pyi}.py"
          done

          flake8 .
          black --check --diff .
          isort --check --diff .

          popd || exit
